#!/bin/bash
#
# Perform build, run, clean.
# author: Javier Chavez
# email: javierc@cs.unm.edu

make_sources () {
    # find all the files but exclude emacs backup files
    find . ! -name "*#*" -name "*.java" > files.txt
}

build () {
    rm -rf dist/
    mkdir dist
    make_sources
    mkdir dist/data
    cp -rf data/* dist/
    cp -rf libs dist/
    if [[ -n $(groups $(whoami) | grep foodgame) ]]; then
	    chgrp -R foodgame dist
	    chmod -R g+rwx dist
    fi

    javac -classpath ".:libs/*" @files.txt -d ./dist
    rm files.txt
}


run_server_n_build() {
    java -classpath "./dist:./dist/libs/*" starvationevasion/server/Server "$1"
}

run_server () {
    build
    # java -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -Xms128m -Xmx2g -Xcomp -classpath ./dist starvationevasion/server/Server "$1" "$2"
    java -classpath "./dist:./dist/libs/*" starvationevasion/server/Server "$1"
}

run_client () {
    build
    java -classpath ./dist starvationevasion/server/Client "$1" "$2"
}

clean () {
    rm -rf dist/
}

if [ "$1" == "build" ]
then
    build
elif [ "$1" == "server" ]
then
    if [ "$#" -eq 2 ]
    then
        run_server "$2"
    else
        run_server 5555
    fi
elif [ "$1" == "nb_server" ] 
then
    if [ "$#" -eq 2 ]
    then
        run_server_n_build "$2"
    else
        run_server_n_build 5555
    fi
elif [ "$1" == "client" ]
then
    if [ "$#" -eq 3 ]
    then
        run_client "$2" "$3"
    else
        run_client localhost 5555
    fi
elif [ "$1" == "clean" ]
then
    clean
else
    echo "Command not found"
fi
